#!/usr/bin/env bash
# run.sh — Start metamorphosis-agent (portable)
# Template — generated by setup.sh
cd "$(dirname "$0")"
export OPENCLAW_STATE_DIR="$(pwd)/.openclaw"
export OPENCLAW_DIR="$(pwd)/.openclaw/workspace"
export OPENCLAW_WORKSPACE_DIR="$(pwd)/.openclaw/workspace"
export PATH="$(pwd)/.local/bin:$PATH"
export npm_config_cache="$(pwd)/.npm-cache"
# Mem0 data directory
export MEM0_DIR="$(pwd)/.mem0"

OPENCLAW_BIN="$(pwd)/.local/bin/openclaw"
if [[ ! -f "$OPENCLAW_BIN" ]]; then
    if command -v openclaw >/dev/null 2>&1; then
        OPENCLAW_BIN="$(command -v openclaw)"
    else
        echo "ERROR: OpenClaw binary not found." >&2
        exit 1
    fi
fi

exec "$OPENCLAW_BIN" "$@"
